### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(RosQML2)
add_subdirectory(RosQML2Content)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	RosQML2plugin
	RosQML2Contentplugin)