[Controls]
Style=Material

[Material]
Theme=Light
Accent=#3498DB         ; Blue accent color
Primary=#607D8B       ; Blue Grey for primary elements
Foreground=#3E2723    ; Brown color for text and other foreground elements
Background=#F5F5F5    ; Light grey background for the overall UI
